/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TargetsRouteImport } from './routes/targets'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ScansRouteImport } from './routes/scans'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as OnchainRouteImport } from './routes/onchain'
import { Route as EvidenceRouteImport } from './routes/evidence'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ScansIdRouteImport } from './routes/scans.$id'

const TargetsRoute = TargetsRouteImport.update({
  id: '/targets',
  path: '/targets',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ScansRoute = ScansRouteImport.update({
  id: '/scans',
  path: '/scans',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const OnchainRoute = OnchainRouteImport.update({
  id: '/onchain',
  path: '/onchain',
  getParentRoute: () => rootRouteImport,
} as any)
const EvidenceRoute = EvidenceRouteImport.update({
  id: '/evidence',
  path: '/evidence',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScansIdRoute = ScansIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ScansRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/evidence': typeof EvidenceRoute
  '/onchain': typeof OnchainRoute
  '/reports': typeof ReportsRoute
  '/scans': typeof ScansRouteWithChildren
  '/settings': typeof SettingsRoute
  '/targets': typeof TargetsRoute
  '/scans/$id': typeof ScansIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/evidence': typeof EvidenceRoute
  '/onchain': typeof OnchainRoute
  '/reports': typeof ReportsRoute
  '/scans': typeof ScansRouteWithChildren
  '/settings': typeof SettingsRoute
  '/targets': typeof TargetsRoute
  '/scans/$id': typeof ScansIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/evidence': typeof EvidenceRoute
  '/onchain': typeof OnchainRoute
  '/reports': typeof ReportsRoute
  '/scans': typeof ScansRouteWithChildren
  '/settings': typeof SettingsRoute
  '/targets': typeof TargetsRoute
  '/scans/$id': typeof ScansIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/evidence'
    | '/onchain'
    | '/reports'
    | '/scans'
    | '/settings'
    | '/targets'
    | '/scans/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/evidence'
    | '/onchain'
    | '/reports'
    | '/scans'
    | '/settings'
    | '/targets'
    | '/scans/$id'
  id:
    | '__root__'
    | '/'
    | '/evidence'
    | '/onchain'
    | '/reports'
    | '/scans'
    | '/settings'
    | '/targets'
    | '/scans/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EvidenceRoute: typeof EvidenceRoute
  OnchainRoute: typeof OnchainRoute
  ReportsRoute: typeof ReportsRoute
  ScansRoute: typeof ScansRouteWithChildren
  SettingsRoute: typeof SettingsRoute
  TargetsRoute: typeof TargetsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/targets': {
      id: '/targets'
      path: '/targets'
      fullPath: '/targets'
      preLoaderRoute: typeof TargetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scans': {
      id: '/scans'
      path: '/scans'
      fullPath: '/scans'
      preLoaderRoute: typeof ScansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onchain': {
      id: '/onchain'
      path: '/onchain'
      fullPath: '/onchain'
      preLoaderRoute: typeof OnchainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evidence': {
      id: '/evidence'
      path: '/evidence'
      fullPath: '/evidence'
      preLoaderRoute: typeof EvidenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scans/$id': {
      id: '/scans/$id'
      path: '/$id'
      fullPath: '/scans/$id'
      preLoaderRoute: typeof ScansIdRouteImport
      parentRoute: typeof ScansRoute
    }
  }
}

interface ScansRouteChildren {
  ScansIdRoute: typeof ScansIdRoute
}

const ScansRouteChildren: ScansRouteChildren = {
  ScansIdRoute: ScansIdRoute,
}

const ScansRouteWithChildren = ScansRoute._addFileChildren(ScansRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EvidenceRoute: EvidenceRoute,
  OnchainRoute: OnchainRoute,
  ReportsRoute: ReportsRoute,
  ScansRoute: ScansRouteWithChildren,
  SettingsRoute: SettingsRoute,
  TargetsRoute: TargetsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
